/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Couch.glb -o src/components/couch.jsx -k -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CouchLarge(props) {
  const { nodes, materials } = useGLTF('/models/Couch.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Node001" position={[0.156, 0.017, 0.031]} rotation={[-1.539, 1.032, 1.544]} scale={0.835}>
        <mesh name="Node-Mesh002" geometry={nodes['Node-Mesh002'].geometry} material={materials['Material.002']} />
        <mesh name="Node-Mesh002_1" geometry={nodes['Node-Mesh002_1'].geometry} material={materials['Traditiona.001']} />
        <mesh name="Node-Mesh002_2" geometry={nodes['Node-Mesh002_2'].geometry} material={materials['Traditiona_1.001']} />
        <mesh name="Node-Mesh002_3" geometry={nodes['Node-Mesh002_3'].geometry} material={materials['Material.001']} />
        <mesh name="Node-Mesh002_4" geometry={nodes['Node-Mesh002_4'].geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Couch.glb')
