/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/easel.glb -o src/components/easel.jsx -k -r public 
*/

import React from 'react'
import { Html, useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'
export function Easel(props) {
  const { nodes, materials } = useGLTF('/models/easel.glb')
  const screenTexture = useTexture("textures/easleTexture.png");
  const basicMaterial = new THREE.MeshBasicMaterial({ color: 0xffffff  });
  // const material= 
  return (
    <group {...props} dispose={null}>
      <mesh scale={0.80} position={[-0.25, 0.95, 0.96]} >
        <planeGeometry args={[2.55, 1.55]} />
        <meshBasicMaterial map={screenTexture} />
      </mesh>
{/* 
      <Html position={[-2.5, 2.2, 0.01]}  rotation={[0, 0, 0]} >
        <div
          style={{
            width: '300px',
            height: '100px',
            background: 'transparent'
          }}
        >
        <video src="/textures/textAnim.mp4" autoPlay  muted playsInline style={{ width: '100%', height: '100%',scale:5 }} />

        </div>
      </Html> */}
      <mesh name="group1441049998" geometry={nodes.group1441049998.geometry} material={basicMaterial} />
      <mesh name="group1958263894" geometry={nodes.group1958263894.geometry} material={materials.mat20}   />
    </group>
  )
}

useGLTF.preload('/models/easel.glb')
